app = "comprehendo"
primary_region = "lhr"

[build]

[http_service]
internal_port = 3000
force_https = true
# auto_stop_machines = "stop"
# auto_start_machines = true
min_machines_running = 2
max_machines_count = 2
processes = ["app"]

[env]
PORT = "3000"

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 500

[mounts]
source = "litefs"
destination = "/var/lib/litefs"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
