# .github/workflows/e2e.yml
name: E2E Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 15 # Adjust as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Next.js application
        run: npm run build
      - name: Run Playwright tests
        # Start server in background, wait, run tests
        # Assumes default port 3000
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          ADMIN_JWT_TOKEN: ${{ secrets.ADMIN_JWT_TOKEN }}
          NON_ADMIN_JWT_TOKEN: ${{ secrets.NON_ADMIN_JWT_TOKEN }}
        run: |
          npm start &
          npx wait-on http://localhost:3000 -t 60000 # Wait for server up to 60s
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always() # Upload results even if tests fail
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
