# .github/workflows/e2e.yml
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Next.js application # Build needed for running tests with start
        run: npm run build
      - name: Run Playwright tests
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          ADMIN_JWT_TOKEN: ${{ secrets.ADMIN_JWT_TOKEN }}
          NON_ADMIN_JWT_TOKEN: ${{ secrets.NON_ADMIN_JWT_TOKEN }}
        run: |
          npm start &
          npx wait-on http://localhost:3000 -t 60000 # Wait for server up to 60s
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: test # Run only after tests pass
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Run only on push to main
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Cache can be helpful here too
      - name: Install dependencies
        run: npm ci # Using ci for consistency and safety
      # Cache build step from fly.yml - might speed up deployment build
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-nextjs-
      # No need for verify/test here, covered by 'test' job
      - name: Build Next.js application # Re-build necessary for deployment context
        run: npm run build
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --dockerfile Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
