name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # Add build-time environment variables for GitHub OAuth
          GITHUB_ID: ${{ secrets.GITHUB_OAUTH_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_OAUTH_SECRET }}
          NEXTAUTH_URL: https://comprehend.fly.dev
